# Generated by Django 5.0.6 on 2024-05-14 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroinfo_app', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.CharField(max_length=100)),
                ('tipodegraoplantado', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokensensores', models.CharField(max_length=500)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='agroinfo_app.property')),
            ],
        ),
    ]
